# Generated by Django 3.0.8 on 2020-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200723_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
